/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.platner.hellorest;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        HelloRestApp app = new HelloRestApp();
        assertNotNull("app should have a greeting", app.getName());
    }
}
